<?php /* Smarty version 2.6.20, created on 2017-04-05 13:36:45
         compiled from header-menu.tpl */

$this->_cache_serials['C:\wamp\phpmelody.dev/Smarty/templates_c\%%E3^E32^E328AEF9%%header-menu.tpl.inc'] = '53d9e3967f76c69f45fae69d34712624';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'dropdown_menu_video_categories', 'header-menu.tpl', 19, false),array('function', 'dropdown_menu_article_categories', 'header-menu.tpl', 27, false),)), $this); ?>
<?php
function _smarty_tplfunc_53d9e3967f76c69f45fae69d34712624_0(&$_smarty)
{
echo smarty_art_html_list_categories(array(), $_smarty);
}



?>
