<?php /* Smarty version 2.6.30, created on 2017-08-04 07:46:07
         compiled from header.tpl */

$this->_cache_serials['C:\wamp\phpmelody.dev/Smarty/templates_c\%%F7^F7F^F7F34188%%header.tpl.inc'] = 'efc4f670af7b163eb410f8ecc886d525';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'default', 'header.tpl', 76, false),array('modifier', 'escape', 'header.tpl', 93, false),array('function', 'dropdown_menu_video_categories', 'header.tpl', 385, false),array('function', 'dropdown_menu_article_categories', 'header.tpl', 393, false),)), $this); ?>
<?php
function _smarty_tplfunc_efc4f670af7b163eb410f8ecc886d525_0(&$_smarty)
{
echo smarty_art_html_list_categories(array('max_levels' => 3), $_smarty);
}



?>
